language: php

sudo: false

branches:
    only:
        - master

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.1
    - 7.2
    - 7.3
#    - nightly

env:
    - DB=mysql
    - DB=sqlite
    - DB=pgsql

before_install:
#    - if [[ $DB == 'mysql' && $MYSQL_VERSION == '5.7' ]]; then ./tests/travis/install-mysql-5.7.sh; fi
    - if [[ $DB == 'mysql' ]]; then mysql -u root -e 'select version()'; fi
    - if [[ $DB == 'pgsql' ]]; then psql -U postgres -c 'SHOW SERVER_VERSION'; fi
    - composer self-update

install: composer update $COMPOSER_FLAGS --prefer-dist

script: ./vendor/bin/phpunit -c tests/travis/$DB.travis.xml

matrix:
    fast_finish: true
#    allow_failures:
#        - php: nightly